<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KualaLumpurListingsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // KL city_id = 11, area_id = 11 (وسط كوالالمبور)
        // category_id = 1 (restaurant)
        // criteria ids: 1=halal, 2=prayer_room, 3=family_section,
        //               4=arabic_staff, 5=alcohol_free, 6=modest_friendly

        $listings = [
            [
                'name_ar' => 'Halab KL Arabic Restaurant',
                'address_ar' => '35, Jalan Berangan, Bukit Bintang, 50200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60321104146',
                'latitude' => 3.1476499,
                'longitude' => 101.7086753,
                'overall_rating' => 4.6,
                'reviews_count' => 7187,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm2i7GVVZpra9usBY7Vcgdo1EjEdLH4uO1Tar0iFO4ZO-V9BCOcd1SXQyCw_DRXQc917QgFMSfvIh3zBjxzs2ddu6roBqne7wWOJVyr8dofL8GlIwihwnXOQtUN88R--Mu3pSREag=w408-h306-k-no',
                'website' => 'https://halab.my/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Halab Beremi Arabic Restaurant',
                'address_ar' => '7, Jalan Beremi, Bukit Bintang, 50200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60179926008',
                'latitude' => 3.1475564,
                'longitude' => 101.7103145,
                'overall_rating' => 4.7,
                'reviews_count' => 3237,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlgervJbSICUnH0FLxLTeqfk-RR8hKMAeSWU2lXHh0bBwXktAfuBXmOsZEXnmbo4p7L_08D7P29q524q6CiiU-KZinh2WziGppOQ3RcoiG2sVmUMstXuz_Zv17KBE-gPRzlIA3ERQ=w408-h306-k-no',
                'website' => 'https://halab.my/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Hadramawt Restaurant',
                'address_ar' => 'G12-G13, Brem Mall, Jln Kepong, Kepong, 52000 Wilayah Persekutuan, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60175004011',
                'latitude' => 3.2045959,
                'longitude' => 101.667054,
                'overall_rating' => 4.9,
                'reviews_count' => 2604,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnYrfQpEcl-8jN-t5ycgQvTKSaDbVbKWLMfLrMgDIs8V3zdWIGiLe8qWsF_afZA0EWRgBAjJeQTBx_nEs3gnNbpStjGf7pZtI9pFTabIXi4Mli-jSQ1kSVEiculNjfeii3kUkz-=w408-h272-k-no',
                'website' => 'http://hadramawt.com.my/',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Lazeez Arabic Restaurant and Grill',
                'address_ar' => '148, Jln Bukit Bintang, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+601111192301',
                'latitude' => 3.1474981,
                'longitude' => 101.7120078,
                'overall_rating' => 4.7,
                'reviews_count' => 2045,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlOPAjYrZsQbdis-iRhIHu07O25Ln0-M1PL1Hrfp-ntLfoNmfQclEpj7X3iaqw1D9M0W5kQ6lqK_eczg6aWFJE293zKyD161LbTuXTixZbv1dujLC2Q7AoM8qmqTjEKWYN5Xq4D=w408-h306-k-no',
                'website' => 'http://www.lazeezarg.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Tarbush Starhill',
                'address_ar' => 'Lot No. LG06, Lower Ground Floor, Starhill Gallery, 181, Jln Bukit Bintang, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60397714988',
                'latitude' => 3.1472495,
                'longitude' => 101.7138979,
                'overall_rating' => 4.8,
                'reviews_count' => 1656,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkMUVkq6J-wIK4D27DVTmAhm1HrYlr3nLUnH2o94CAhngcboINwHALTaRh2ffcdbYecXH97eZJ2Z1Q8Cj2l-Qfsj9HquhmAQr15L2fviTLp1mjSUUE6alj6hmvRfh3IpHd3A2sp=w408-h306-k-no',
                'website' => 'https://tarbushstarhill.shop/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Al - Sultan Restaurant - Bukit Bintang',
                'address_ar' => 'Lot 100-A, Seksyen 67, Jln Sultan Ismail, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60107044164',
                'latitude' => 3.1463077,
                'longitude' => 101.7112424,
                'overall_rating' => 4.8,
                'reviews_count' => 3567,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkJiNoK6QZb05WXmMxz_XE0tXvglUgVSXyxmKkRRKwc04yUGlLPNcvjvupSs8SMuSzPiNIu0SbpKm_3j-QNb3MjHHn7fNjuY8wPfPb6d-2gIlOlYxYWHmNH4cZLRKqfVXeuexJT3FN6sVUB=w408-h544-k-no',
                'website' => 'https://www.alsultanglenmarie.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Samad Al Iraqi Restaurant مطعم صمد العراقي',
                'address_ar' => 'G-3, Menara Prestige, 1, Jalan Pinang, 50450 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+601111100092',
                'latitude' => 3.1556557,
                'longitude' => 101.7095427,
                'overall_rating' => 4.7,
                'reviews_count' => 13243,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlxcFTmrFhgfr5Y6589eglWbjRAjiM95KpzMKVG7_PZpqrD8CZwkj-DCf6_4ED0p6h7yGjxepbu1vbVzFyCIiIYUdKFxB5m9uPIrWEV6gt_ICDcysOmboWPMsSfRRDZjmimDtnC=w408-h306-k-no',
                'website' => 'http://www.samadaliraqirestaurant.com.my/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Arabian.B KLCC Restaurant',
                'address_ar' => 'lot-19,level-2, Avenue K, shopping mall, 50088 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60122143088',
                'latitude' => 3.1594951,
                'longitude' => 101.713382,
                'overall_rating' => 4.7,
                'reviews_count' => 189,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk9AdvPb7rBhBUwZPpWrd3AMy0ofr1739ASBuswaeTVZSBdVLKPgxAVUtFyFRw-b7xlZ1EYslEGH5vT3IpZ0jXgiVNdi8UPTxb1mgz81YiTJeXHQBUPSi3YNMygJEyJ7I_9YVCk=w408-h544-k-no',
                'website' => 'https://wa.me/message/2IGM5RNL5LGEK1',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Restoran Hadramawt Palace',
                'address_ar' => 'Lot No, 251, Jln Bukit Bintang, Imbi, 55100 Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia',
                'phone' => '+60321433333',
                'latitude' => 3.147689,
                'longitude' => 101.7215554,
                'overall_rating' => 4.4,
                'reviews_count' => 2810,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmh2vth3ouiUaYVJ2Cs6k2Cce5OVpK3hR8wmydWiNyhyBtfx9DQB5LbDyDCZtGOjfuL9otL4cPoEvCVO-fIVmuWjpE3ioI3PWXT-X8bk5qFTbeVzzTkrOv9t6bm5BpxldyAEXM6Aw=w408-h271-k-no',
                'website' => 'https://hadramawtpalace.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'مطعم بوابة حلب Halab Gate Restaurant',
                'address_ar' => '51d, Jln Sultan Ismail, Bukit Bintang, 50250 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60321104412',
                'latitude' => 3.1475254,
                'longitude' => 101.7108837,
                'overall_rating' => 4.7,
                'reviews_count' => 2501,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlBH29KOK4KE9sGlAxyWi_O97UC7Z2ueGWutue-mtexU4nMrQEw1tVUNeHorjtXc8JsZ26f5cbznEtLpPqdtFZRHpwR0UKz9nrQJePqy6UeZdut3DDKrRvzmrkwd3eiFA6DTFY7qEg9Dsgx=w408-h272-k-no',
                'website' => 'https://linktr.ee/halabgaterest',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Bedouin Arabian Cuisine',
                'address_ar' => '6, Jalan Wan Kadir, Taman Tun Dr Ismail, 60000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60127374712',
                'latitude' => 3.1389097,
                'longitude' => 101.6301454,
                'overall_rating' => 4.5,
                'reviews_count' => 2162,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmnagxKGN1DrSHDtC7_Q7-V_xUlV_X_kXXN-uz5tWOk2Pibum_LiJCBYqJ9KuAWhQb7CYeEHJV_z5X3UYgluzUY6hRDz1Jwp98IyNkgprG9kuAIbQYkuIYlO0QrP9gCUIxc2u-w=w429-h240-k-no',
                'website' => 'https://www.bedouinttdi.com/menu',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Arabella Restaurant',
                'address_ar' => 'NO 28-0 Ground floor, Jalan Nagasari, Bukit Bintang, 50250 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60133750750',
                'latitude' => 3.1487864,
                'longitude' => 101.7091489,
                'overall_rating' => 4.5,
                'reviews_count' => 711,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnESJZXK9wD3T3AvhA6_SaABCnG-OV0_i_cNjtnBnepvQY4eimtKG_XQpivw51gmE1hNEFll_oy6i7BIeS2bF4z6DPztOv_cF8tJT5z7KhjfUHv0kCuqJkRCvR1JBJYdUlItIU-=w408-h273-k-no',
                'website' => 'https://arabellarestaurant.shop/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Hadramawt Restaurant',
                'address_ar' => 'B-G-20, Razak City Residences, Jln Razak Mansion, Sungai Besi, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60175004011',
                'latitude' => 3.1080338,
                'longitude' => 101.7060865,
                'overall_rating' => 4.9,
                'reviews_count' => 1395,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmgA_--bwAxLlFJ8rCMrce3G0f3Lf-4S8j2QGVfoklKNeqATjnN9lAztTkuu15ySp5jIV-OIo3RCADvB0K9-V84sfGB0FHuj4fv5L1rCDg7dLrWLxvc8IrlAnvWJUFlV44eutlHyQmyrH4=w408-h298-k-no',
                'website' => 'https://www.hadramawt.com.my/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Tarbush Restaurant Bukit Bintang',
                'address_ar' => '138, Jln Bukit Bintang, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60321428558',
                'latitude' => 3.1473177,
                'longitude' => 101.7117942,
                'overall_rating' => 4.2,
                'reviews_count' => 5558,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk2qoYK4YM6O5-OtAg94dvYwQ4amtzZ9sKeVMZ5DOhuG-ViTIsB9CqoKB7GcOfGfVprkW2bgNxYypaXs1LtIHTYxdBL2mTq4GAM02nzWwk6lDyE5usAWmlZW94Sh6gBogT0Vu92FA=w408-h271-k-no',
                'website' => 'https://gotarbush.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Al Halabi Gourmet Restaurant',
                'address_ar' => 'Lot 7 . 01 . 06, 168, Jln Bukit Bintang, Bukit Bintang, 55100 Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia',
                'phone' => '+60321130061',
                'latitude' => 3.1496284,
                'longitude' => 101.7129796,
                'overall_rating' => 4.3,
                'reviews_count' => 2118,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmd97oNCsZpTHOFeChz0ZgFlUvbWDfhlh7dnrofpObWvORDMUbxK_TML2H31RoX72dWyXQLECKIMNc5USphfBfVfwXg84kkHW-rwAjWl7gENU5XluFG_5DoIHYBhfMWbvYKj680=w408-h272-k-no',
                'website' => 'https://alhalabigourmetrestaurant.shop/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Middle East Grill',
                'address_ar' => '美食中心 Kepong Food Court, Jalan Metro Perdana Barat 14, Taman Indah Perdana, 52100 Kuala Lumpur, Wilayah Persekutuan, Malaysia',
                'phone' => '+60183639134',
                'latitude' => 3.2152249,
                'longitude' => 101.6375398,
                'overall_rating' => 5,
                'reviews_count' => 4,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWndAQoRurQMVD_3pKSJmghH-GaAlvUZi6Q2A65WGViI4D_xz20u-8Ty9tGJNAOp4eFgZ1ED5w187L2Wy0zxXGyXNrPgDkmYj9cvT3DfkzDhNsOcElJmwyV70NOYRp08OKuPXiNiwQ=w533-h240-k-no',
                'website' => 'http://www.fb.com/meg.kepong',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Royal Bedouin',
                'address_ar' => 'B1-60, Plaza Damas, Jalan Sri Hartamas 1, Taman Sri Hartamas, 50480 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60123314712',
                'latitude' => 3.1632015,
                'longitude' => 101.6556682,
                'overall_rating' => 4.8,
                'reviews_count' => 939,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnYkojLhIKWSBcTxXpDacFeKRZaQ5iDKBDL_NfUv5bLM1kUkk1b7gIqZtmKRHBe5QxzUK4u_GhaJUIp0IHrHyIMVYofKMPxNr6_lm5scrDLku6rGmBKBK0OHOnTux1-iaW9PItUGXthM0Qq=w426-h240-k-no',
                'website' => 'https://royalbedouin.oddle.me/en_MY/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Al Rawsha Restaurant',
                'address_ar' => '8, Jalan Kampung Pandan, Kelab Golf di Raja Selangor, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60392006600',
                'latitude' => 3.1388496,
                'longitude' => 101.7219266,
                'overall_rating' => 4.2,
                'reviews_count' => 4023,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkOYahF_IaaiDou6m3R0fzBhon97_KkXqco2UB-Tx965DiXgkKvwe9Zbq_2-WnCGiAhLTofnoFEWFRE1tkiiffCXV3lOQL5gnsaiaYqyDvFzOE6X94FP9a5ROo8EoM17RKTn1FU=w426-h240-k-no',
                'website' => 'https://alrawsha-restaurant.com.my/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Al-Amar',
                'address_ar' => 'Lot 6.10, level 6, Pavilion Kuala Lumpur, 168, Jln Bukit Bintang, Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60172840874',
                'latitude' => 3.1485784,
                'longitude' => 101.7130998,
                'overall_rating' => 4.2,
                'reviews_count' => 1516,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWngvmXLsxD39bsqc749ciqoVqSIDtw4TUsZscV9HmfB7Z3ej8jofu_mTYz87KtRI7-mDFQV7oD0z3EAjWWA1W9u2LCGALQvLjnZiyYZaitUlFf9XDf70z_U0cKu1w1dNJsiRHI=w408-h306-k-no',
                'website' => 'http://www.alamarkl.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'D\'ARAB STATION',
                'address_ar' => '36, Jln Damai Raya 2, Alam Damai, 56000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60164485874',
                'latitude' => 3.0629344,
                'longitude' => 101.7440723,
                'overall_rating' => 4.3,
                'reviews_count' => 477,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmCqRP2KZYrOHbqhV-QAhJHZGt-tdYprU-4N0Ez7fMnD9J05v1tITzyZqUFACBoCsPb5hzw8uKVaSYNE58GXDEsE8p9h76ZngXjw_cWSV5PEIO4me8-QK88p5ae6fLvvrp8Uc9O=w408-h305-k-no',
                'website' => 'http://www.facebook.com/DARABSTATION',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Shawarma Restaurant',
                'address_ar' => '10, Jalan Menara Gading 1, Taman Connaught, 56000 Cheras, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60108818819',
                'latitude' => 3.0806504,
                'longitude' => 101.7331541,
                'overall_rating' => 4.8,
                'reviews_count' => 1567,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn0RYlaeSaE6Ck7Z3COlUCRLp2SwxUWaszfS_SI7GNPWFmwHIknc5KRb3DIA0ScYBobhqJZ_pWShCz1hB2Gvjp3OYiOY-e4y829982WqzF_vaHWS90-Dh2Ry5miVoNxCK5CyWKUr40cuU8_=w408-h306-k-no',
                'website' => '',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Onfire Restaurant',
                'address_ar' => 'G-29, Residensi Majestic Maxim, 45, Jalan 9, Taman Bukit Cheras, 56000 Cheras, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60391076483',
                'latitude' => 3.0771738,
                'longitude' => 101.7424913,
                'overall_rating' => 4.8,
                'reviews_count' => 660,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm5IquqVbZdBaLWwqfS9yy3QVgI-wJfTcv51P-vNKJ0U2cBwNvu9CA684RsuFXvNFHryRYtph9nzdpLUOe8sESFQpA21Mv4n4A4NwU-YL_x23WYk4pgkGYpwJP9W_9dIyneFaArXA=w408-h306-k-no',
                'website' => '',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Nasi Arab Chef Abdullah',
                'address_ar' => 'Taman Desa Tasek, 57000 Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia',
                'phone' => '+60183135064',
                'latitude' => 3.0724767,
                'longitude' => 101.7155534,
                'overall_rating' => 4.5,
                'reviews_count' => 50,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkYJwh6HZdWumyLx-ZWCcBMAh7Ti-f4qpndRDr3pwKW_2eNoK6XJrAIRUUXrrYMLarKARlT6Qi7ok9slJFhlLBckVTfYGxSxARx9LiqHV7vjK1Q0ajNuH4Pl9XcM150vocnXccmCEUXLUKY=w541-h240-k-no',
                'website' => '',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Hadramawt Kitchen • Bangsar | Middle Eastern & Yemeni Cuisine',
                'address_ar' => '50, Jalan Maarof, Bangsar, 59100 Wilayah Perseketuan, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+601153312244',
                'latitude' => 3.1319286,
                'longitude' => 101.6722793,
                'overall_rating' => 4.9,
                'reviews_count' => 599,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk7f4nME6ZUvzrIalq63qNMEh6qNxFIvHiSZBlhEK3vQ8fvVKWK4TQLLllmbkFpbcxR7s8H4IJsk_goTXbLxfu6Smfv8z9fV38G01nQ7AmfsLzftdRseBLjfZ2YPcXdFn7MmPaNq9z09m4=w408-h306-k-no',
                'website' => 'https://www.hadramawtkitchen.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Murni Discovery Kepong',
                'address_ar' => '24, Jalan Metro Perdana 8, Taman Usahawan Kepong, 52100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60125299606',
                'latitude' => 3.2152504,
                'longitude' => 101.6427418,
                'overall_rating' => 4.1,
                'reviews_count' => 2476,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk2zgmw-M1nzcDo7EFT3EbIXAOsGAAbl_Xt26QvyiRkzUTjrxDOP7BDH8X1KgF6eVHL9Bn0SVKt-Wi4zZiCj9lzwLZgtKIpZhe2EOh-ugzFmzfOPCYoayaOVyco1X7pUdLCafyn=w408-h306-k-no',
                'website' => 'http://www.murnidiscovery.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Nasi Kandar Mamak Cafe | Aradia Residence Lake City',
                'address_ar' => '102, Jalan Sibu, Taman Wahyu, 68100 Batu Caves, Selangor, Malaysia',
                'phone' => '+60386796689',
                'latitude' => 3.2153405,
                'longitude' => 101.6695776,
                'overall_rating' => 4.3,
                'reviews_count' => 274,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkPLEk4WXvevbAKJQEiseN0eBH1jNAxKvt7m9H_4DhxXoQIT8Uh8R96A5V_Vb_fOkQwzj7GYeg0Anus2qBOrUPx7LNzUf-iVASQF0VcDepv8OHJVD65uVCTdqniVOa--QMF4jv53AbnaFjU=w408-h306-k-no',
                'website' => 'https://scanmenu.my/nasi-kandar-mamak-cafe-menu-lake-city/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Restoran Ali Maju Sdn Bhd',
                'address_ar' => 'Vista Magna, Jalan Prima 5, Metro Prima, 52100 Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia',
                'phone' => '+60127869033',
                'latitude' => 3.2133299,
                'longitude' => 101.6430164,
                'overall_rating' => 3.5,
                'reviews_count' => 734,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnwduLxG8P8GLkHtRAVBpshjDJmUlsEHiLTNPAI6o87jGh21DRGEEBNkGPtDPMIAaQtkFJy_l8FuSLvq1VciORIsKdpQgQ73z8kYPL9JIg0MzAZWyg0bj0cPsDkbGGGjfGfIV3k=w408-h306-k-no',
                'website' => 'http://www.alimaju.com/',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Palmyra Restaurant',
                'address_ar' => 'Jalan 3/149e, Taman Sri Endah, Bandar Baru Sri Petaling, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60182626458',
                'latitude' => 3.0638922,
                'longitude' => 101.6973791,
                'overall_rating' => 4.7,
                'reviews_count' => 51,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnbyi6wQJ9YhLourGMAhf4t_zJgQAVM1NQeTJyvNBzIslzxETvz9U3OHtMG_rMJz0fyc9TqRYmms3TmZgNQyZiY5JJI0t5_XYhuO9uwNvDoT7-9KeBT5Rj3rzfhYgNqnT3heO_p=w408-h272-k-no',
                'website' => 'https://r.grab.com/g/6-20251222_165154_44C9976072B44F91811451BCF6F33364_MEXMPS-1-C25KRBKHCAUWJE',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Restoran Dream',
                'address_ar' => '01-15, Jalan 3/149e, Taman Sri Endah, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+601115562724',
                'latitude' => 3.0634945,
                'longitude' => 101.6973578,
                'overall_rating' => 4.2,
                'reviews_count' => 316,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlImJpNSk9XtMbsHp2f1raz4AZLEJK7bnMDsNVvUfXc2y9iMvtziYubBzHxF0PwGlMSMIzHDS640CL90gDhy0_bUlng2GJAWKIu_SeLKDnHO5eEpdYAwtTWj3c5bma8dwfAAIw=w408-h306-k-no',
                'website' => 'https://www.facebook.com/restorandream/',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'S•BRJ Bistro Corner • Alam Damai',
                'address_ar' => '26, Jln Damai Raya 2, Alam Damai, 56000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60391082475',
                'latitude' => 3.0621003,
                'longitude' => 101.7440816,
                'overall_rating' => 4,
                'reviews_count' => 1908,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlS7DFOLlxya6_TFpr34h-xx9h4cD_2AyU-qxMYyK4UKE7AVF9PYjkuV01et3__Lwhf4FH0Dzgequt8HkvXC6tsmbE1aUcSwvT22F1tthdNpLaPgjZNxZ3QM5kTdwNyj9YHUru6FQ=w408-h544-k-no',
                'website' => '',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Restoran Al-Safa',
                'address_ar' => 'Jalan 3/149e, Taman Sri Endah, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+601128964345',
                'latitude' => 3.0638916,
                'longitude' => 101.6974062,
                'overall_rating' => 3.8,
                'reviews_count' => 836,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnGBWIl-1RhUUzwNePrM7449NFQn7IqNViDjMLtpMNHkWJfAgLQhJ-khhr7hZ4MLyaD8UkbJa25PmO3GnCVXh1AUuEUWEysJZsODcW40SUu28XGCVrWxGkubJFbfXPwQEdEvVmY=w426-h240-k-no',
                'website' => '',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Cik Melur Alam Damai',
                'address_ar' => 'No 42A, Jln Damai Raya 2, Alam Damai, 56000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60162792577',
                'latitude' => 3.0631955,
                'longitude' => 101.7441145,
                'overall_rating' => 3.8,
                'reviews_count' => 349,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnWSWSBH7hVmX9KQ0koYxbWTGhyHouYNPz3wv3XVDSUE_Q6Gn8jAwQkQSn-ru1H7cWE_ufyyLC8fJe8A9W4lPvI9e6sM4hl7cTQl2Z24W4IpxIoWRNH9A0-jltrUrXHfmhg7rQE=w408-h544-k-no',
                'website' => '',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Nasi Ayam Suasa Corner Sgbesi',
                'address_ar' => '90, Jalan Suasa, Pekan Sungai Besi, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60123571175',
                'latitude' => 3.0644765,
                'longitude' => 101.7106634,
                'overall_rating' => 4,
                'reviews_count' => 30,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl_qLBS01by0yr_Y3HSNLOznnQMb-EXqB3plQvhNQd1Mwx7KgpvVUcGhujOVwNulHIWFb2AARQVnCokoi5XziUNc6xZ9Vrf5Yu1-w9zPF-aS1l7Kk9K6uxBUJqPgQJmjF7F9YA=w426-h240-k-no',
                'website' => '',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'TAZYEEN',
                'address_ar' => 'TAZYEEN Arabic and Mughal Cuisine Adjacent to City Central Hotel, 82, Jalan Tun Sambanthan, Brickfields, 50470 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60125320786',
                'latitude' => 3.1332525,
                'longitude' => 101.6883283,
                'overall_rating' => 4.7,
                'reviews_count' => 1258,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmXiJLZkAADFTz92agfxHmIrFjpJzQNyvGJI_d600V0dLROZ2FlkKySsgRJsozqH7gpnBJ_oUQTBTAwn-ge9_YvlUnqwm2iSdcS4EFwhIyGliNIF4qbkRnyzAcHj2bnZasoC9qp=w513-h240-k-no',
                'website' => 'http://www.tazyeengroup.com/',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Beirut Habibi',
                'address_ar' => 'No.15 & 15A, Lorong Kurau, Taman Bukit Pantai, 15, Lorong Kurau, Bangsar, 59100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60378029066',
                'latitude' => 3.12259,
                'longitude' => 101.6709805,
                'overall_rating' => 4.6,
                'reviews_count' => 404,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkgS-PbGPWzUSUGkBdZa1TMth3mwgV10RS1r-jRQrUUC-WyCIhuknRKGaV0fPxzASU2LE6ce9ta5F3bC0kFKPGfcOULM__yJWyyC6Hqz9APheNGZ3NPWZX0i9dA-n3lNYPazZ-U0Q=w423-h240-k-no',
                'website' => '',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Arabian Shisha Lounge @ Frame Hotel',
                'address_ar' => '411, Jln Pudu, City Centre, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60186602754',
                'latitude' => 3.1331595,
                'longitude' => 101.7145502,
                'overall_rating' => 4.8,
                'reviews_count' => 2882,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWll4jJpKmymJiZTiiJ5lz5iXzQYb3g3_xyd-vPluOfIZoZHpRakPZ6JdZtMBBSGbd7-RwQMz1g_Ei65kt7VF9jTENhZCTvX_Uj7X5cdQvzxRGU93LCU_TKP8fvUbLLAVyJ2Z5M=w408-h306-k-no',
                'website' => 'https://www.instagram.com/arabianshishalounge/',
                'is_halal' => false,
                'is_family' => false,
            ],
            [
                'name_ar' => 'Rasa Habibi Nu Sentral',
                'address_ar' => 'Lot LG32 & LG32(AL), Level LG, Nu Sentral, 201, Jalan Tun Sambanthan, Brickfields, 50470 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+601121205984',
                'latitude' => 3.1331869,
                'longitude' => 101.6872241,
                'overall_rating' => 4.8,
                'reviews_count' => 635,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmAA4y_itICVLjItUYkb4WvO-g32Zt2RXytdfESCjS1p7pBPjB2Z0RWiy1hkmQV9FfnJknztmnihgvwVQv37epkzqAJML6gVY2GCYxmrnR2f0J5q3_ChL-48d9jRBIPu-2kJS2X00p9cz0e=w408-h272-k-no',
                'website' => 'https://rasahabibi.com/',
                'is_halal' => true,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Al Diafah Restaurant - Sri Petaling',
                'address_ar' => 'Jalan Radin Anum, Bandar Baru Sri Petaling, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60123692617',
                'latitude' => 3.0704658,
                'longitude' => 101.6911209,
                'overall_rating' => 4.3,
                'reviews_count' => 1025,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmHC-rGMpBtNPo0nm58yJHq-7vWlXBZhde944hrsaGXywOo3tRf2sWEDx37t7JJqAcVDCohYUbBivJzCGF89zqiHUMLvrk2NxjKZm2kIWamumY9KDq2KKS5zLzVjfxp7sTWEME=w426-h240-k-no',
                'website' => 'http://aldiafah.placeorder.my/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Tarbush Restaurant - The Exchange TRX',
                'address_ar' => 'Lot.02.0 & PL.03.0, Level 3 and Park Level, The Exchange TRX, Persiaran TRX, Tun Razak Exchange, 55188 Wilayah Persekutuan, Federal Territory of Kuala Lumpur, Malaysia',
                'phone' => '+60189831802',
                'latitude' => 3.1427464,
                'longitude' => 101.718191,
                'overall_rating' => 4.7,
                'reviews_count' => 585,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk0UEmKaQr7b7C7-7GRrbbw45_UQSd-UiH7IV8c6GuW5w1PM4_pTJJmav4OWicw44rLQUkuIKh0njJxLKF03kjEklOYRZHZRiga-K0-Zci59IzSuZGrX4o4OFJHFTIVLjZJ0MSa2JGBJsQ=w408-h544-k-no',
                'website' => 'https://tarbush-my.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Kebab Syria | شاورما سوريا',
                'address_ar' => 'Ground Floor, 11, Jalan Dwitasik, Bandar Sri Permaisuri, 54000 Kuala Lumpur, Federal Territory of Kuala Lumpur, Malaysia',
                'phone' => '+601111701126',
                'latitude' => 3.0992238,
                'longitude' => 101.7128702,
                'overall_rating' => 4.7,
                'reviews_count' => 369,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm5jky_ELE3B1FrYBEuzsN9U3sjhqxCEH12Pb0PRcqMwA9OudwxPBka6oBhHqG3xgGfyvUW_ZvGcJwNyJKCj2hILFMX05gHorpGQrECjNZvOLBrsA9CMQLeIH6KmX70ijwgA-fQJPtHMqvY=w408-h306-k-no',
                'website' => '',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'Turkish Cafe Istanbul',
                'address_ar' => 'LG-08 Glo Damansara, 699, Jln Damansara, Taman Tun Dr Ismail, 60000 Kuala Lumpur, Malaysia',
                'phone' => '+60377311644',
                'latitude' => 3.1324785,
                'longitude' => 101.6296304,
                'overall_rating' => 4.6,
                'reviews_count' => 2193,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlR7SfRjAihEuzX7WB8mv6GNlFlU2hrgNLKGv1ViHZiIRYGJayKwoyhCtYZKgAAfdO9VHsKsi2u1k3cv6lctiq7yVLDqkyY8uJ_jFO_4XGDOrygfQ43hcdZzuT0AqAAAAXyP54Z=w408-h544-k-no',
                'website' => 'https://linktr.ee/turkishcafeistanbul',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'YaHala Restaurant - TTDI',
                'address_ar' => 'G.33A-G.38, Glo Damansara, 699, Jln Damansara, Taman Tun Dr Ismail, 60000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60377337216',
                'latitude' => 3.1332847,
                'longitude' => 101.6296405,
                'overall_rating' => 4.5,
                'reviews_count' => 334,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk9VzPOnuk3QFmzSyTct0gfWlzsg8KJlamDe5M1etRGKKCtCQ6t0RYV2zNvSPvOaLTC4Evc7su5rw3TBbIc4ftj5RmIxXE6oBIfSpfN41GEndj7gtX9L-6qkana86U8eLSRhdp_WKuaNCIz=w408-h265-k-no',
                'website' => 'http://yahalares.com/',
                'is_halal' => false,
                'is_family' => true,
            ],
            [
                'name_ar' => 'RESTORAN NASI ARAB A1',
                'address_ar' => 'Lot 6A, Lorong Bukit A1, Jalan Kuari, Kampung Cheras Baru, 56100 Cheras, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'phone' => '+60183111402',
                'latitude' => 3.1066796,
                'longitude' => 101.7369813,
                'overall_rating' => 4.7,
                'reviews_count' => 27,
                'cover_photo' => 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlNSl430-bm50pBRnY4RRahrh6luOV9T8TEFpyGVAHr54p0ABLbtGKuaMRImCAsW3pl-PTj4oyRpTXOk49ugZ6eJXzj6Gukz-afZo2kpDIeximU-Z3yAZ5AjLLGEjduf82lqXauOs5x201U=w408-h408-k-no',
                'website' => '',
                'is_halal' => true,
                'is_family' => true,
            ],
        ];

        foreach ($listings as $data) {
            $isHalal = $data['is_halal'];
            $isFamily = $data['is_family'];
            unset($data['is_halal'], $data['is_family'], $data['cover_photo'], $data['website']);

            $listing = DB::table('listings')->insertGetId(array_merge($data, [
                'category_id' => 1,
                'area_id' => 11,
                'name_en' => null,
                'description_ar' => 'مطعم عربي في قلب كوالالمبور يقدم أشهى المأكولات العربية الأصيلة.',
                'is_active' => true,
                'promotion_rank' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ]));

            // Seed criteria scores
            $criteria = [
                1 => $isHalal ? 90 : 50,  // halal
                2 => 70,                   // prayer_room
                3 => $isFamily ? 90 : 60, // family_section
                4 => 80,                   // arabic_staff
                5 => $isHalal ? 95 : 60,  // alcohol_free
                6 => 75,                   // modest_friendly
            ];

            foreach ($criteria as $criteriaId => $score) {
                DB::table('listing_criteria')->insert([
                    'listing_id' => $listing,
                    'criteria_id' => $criteriaId,
                    'score' => $score,
                    'votes_count' => rand(5, 30),
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }

        $this->command->info('✅ KL listings seeded: ' . count($listings) . ' restaurants');
    }
}